---
title: "Orbit stabalizers"
format:
  html:
    toc: true
    html-math-method: katex
---

## Group actions

Group actions are vital to understanding and constructing quotient groups.

::: {.callout-note icon="false"}
## Definition

A [**group action**]{style="color: blue"} of a group $(G,\star)$ on a set $A$ is a map $G \times A \to A$ (denoted $g \cdot a$) such that for all $g_1, g_2 \in G$ and $a \in A$

$(1)$ $g_1 \cdot (g_2 \cdot a) = (g_1 \star g_2) \cdot a$, and

$(2)$ $e_G \cdot a = a$

Where $e_G$ is the identity element of $G$.

:::

It is common for $g \cdot a$ to be abbreviated $ga$. This may be confusing at times, as  $(g_1 \star g_2) \cdot a$ above could be abbreviated as $g_1g_2a$, so discretion is required.

Let $G$ be a group acting on the set $A$. For every $g \in G$ we have a map defined

$$
\sigma_g \colon A \to A
$$

$$
\sigma_g(a) = g \cdot a.
$$

::: {.callout-note icon="false"}
## Proposition

Given the above definition for $\sigma_g$,

$(1)$ For each fixed $g \in G$, $\sigma_g$ is a *permutation* of $A$

$(2)$ The map $G \to S_A$ defined by $g \rightarrowtail \sigma_g$ is a homomorphism.
:::

::: {.callout-tip icon="false" collapse="true"}
## Proof

$(1)$ We prove $\sigma_g$ is a permutation of $A$ by showing 

$$
\sigma_g \colon A \times A
$$

Is a bijection. We prove this by showing there exists a two-sided inverse $\sigma_{g^{-1}}$.

\begin{align*}
\sigma_{g^{-1}}(\sigma_g(a)) &= g^{-1}\cdot(g\cdot a)\\
&= (g^{-1}\star g) \cdot a\\
&= e_G \cdot a\\
&= a
\end{align*}

Since $g$ was arbitrary, we may replace $g$ with $g^{-1}$ to obtain another identity map on $A$. Thus $\sigma_g$ is a bijection, and a permutation.

$(2)$ To show the map a homomorphism, we first define $\varphi \colon G \to S_A$, such that

$$
\varphi(g) = \sigma_g.
$$

Then through a series of equivalances

\begin{align*}
\varphi(g_1 \star g_2)(a) &= \sigma_{g_1g_2}(a)\\
&= (g_1 \star g_2) \cdot a\\
&= g_1 \cdot (g_2 \cdot a)\\
&= \sigma_{g_1}(\sigma_{g_2}(a))\\
&= (\varphi(g_1) \circ \varphi(g_2))(a)
\end{align*}

Thus the map is a homomorphism.

:::

A group action of $G$ on a set $A$ intuitvly means that every element of $G$ acts as a permutation on $A$, in some manner consistent with the group operation of $G$. The homomorphism from $G$ to $S_A$ given above is called the *permutation representation* associated to the given group action. 

The definition given above could be more precisely called the *left action* as the group elements are left to the set elements. A *right action* could be defined identically.