---
title: "Quotient groups"
format:
  html:
    toc: true
    html-math-method: katex
---

Quotient groups work like subgroups to obtain a "smaller" group from some base group $G$.

## Definitions 

::: {.callout-note icon="false"}
## Definition 

Let $\varphi$ be a homomorphism from $G$ to $H$. The [**fibers**]{style="color: blue"} of $\varphi$ are the sets of elements of $G$ that map to single elements of $H$.
:::

For example, given the groups $G = (\mathbb{Z},+)$ and $H = Z_n$ be the cyclic group of order $n$ under multiplication. We can then define the map

$$
\varphi \colon \mathbb{Z} \to Z_n
$$

$$
a \rightarrowtail x^a
$$

The *fiber* of $\varphi$ over $x^a$ is therefore

$$
Put fiber 
$$

The homomorphism $\varphi$ has two fibers, we will notate $X_{[1]}$ as the fiber over $[1]$, and $X_{[0]}$ as the fiber over $[0]$. Then

$$
X_{[1]} = \{1,3,5,\cdots\} \quad X_{[0]} = \{0,2,4,\cdots\}
$$

The set of fibers of $\varphi$ forms a group. We define our group operation as follows

$$
X_{a}X_{b} = X_{ab}
$$

Where $X_{ab}$ is the fiber over the product $ab$. This is called the *quotient group* of $\varphi$. Below is a formal proof the collection of fibers forms a group.

::: {.callout-tip icon="false" collapse="true"}
## Proof [Finish]

Prove the set of fibers of $\varphi$ is a group.
:::

We can now look at some properties of homomorphisms

::: {.callout-note icon="false"}
## Definition 

If $\varphi \colon G \to H$ is a homomorphism, the [**kernal**]{style="color: blue"} of $\varphi$ is the set 

$$
\ker\varphi = \{g \in G \mid \varphi(g) = e_H\}
$$

:::

The kernal is therefore the fiber over $e_H$, the identity element of $H$.

::: {.callout-note icon="false"}
## Definition 

If $\varphi \colon G \to H$ is a homomorphism, the [**image**]{style="color: blue"} of $\varphi$ is the set 

$$
\text{im}\,\varphi = \{\varphi(g) \mid g \in G\}
$$

:::

The kernal and image of $\varphi$ are subgroups of $G$ and $H$ respectivly.

::: {.callout-note icon="false"}
## Proposition 

If $G,H$ are groups, and $\varphi \colon G \to H$ is a homomorphism, then  

$$
\ker \varphi \leq G \: \text{ and } \: \text{im} \,\varphi \leq H
$$

:::

::: {.callout-tip icon="false" collapse="true"}
## Proof 

Since $e_G$ is such that $\varphi(e_G) = e_H$, we know $\ker \varphi \not = \varnothing$. If $x,y$ are in the $\ker \varphi$, then $xy^{-1}$ is in the kernal, thus $\ker \varphi$ is a subgroup of $G$.

Now take the image of $\varphi$. Note 

$$
\varphi(e_G) = e_H \in \text{im } \varphi \implies \text{im } \varphi \not = \varnothing
$$

Given $x,y \in \text{im } \varphi$, we know that $xy^{-1}$ is in $\text{im } \varphi$. Thus $\text{im } \varphi \leq H$. 

:::

And we can now provide a formal definition for a quotient group

::: {.callout-note icon="false"}
## Definition

Let $\varphi \colon G \to H$ be a surjective homomorphism with $\ker K$. The [**quotient group**]{style="color: blue"} $G/K$ is the group whose elements are the fibers of $\varphi$ with group operation inherited from $H$.
:::

This definition requires knowing $\varphi$ explictly. You can however define the group operation on fibers in terms of representatives. 

::: {.callout-note icon="false"}
## Proposition

Let $\varphi \colon G \to H$ be a homomorphism with $\ker k$. Let $X \in G/K$ be the fiber above $a \in H$. $X = \varphi^{-1}(a)$. Then for any $u \in X$, 

$$
X = \{uk\mid k \in K\}
$$

:::

::: {.callout-tip icon="false"}
## Proof

Let $u \in X$, then $\varphi(u) = a$. Let

$$
uK = \{uk \mid k \in K\}
$$

We want to show that $X$ is equal to $uK$. We will first show that $uK$ is a subset of $X$. For $k \in K$
$$
\varphi(uk) = \varphi(u)\varphi(k) = \varphi(u) = a 
$$

Thus $uK \subseteq X$. Now to show that $X \subseteq uK$, let $g \in X$ and $k = u^{-1}g$.
$$
\varphi(k) = \varphi(u^{-1})\varphi(g) = a^{-1}a = e_H
$$

Thus $k \in \ker \varphi$ since $k = u^{-1}g$. Thus $X \subseteq uK$

:::

Thus we can write any elements of the quoitent group as the set $uk$ for all $k \in K$.

::: {.callout-note icon="false"}
## Definition

For any $N \leq G$ and $g \in G$,

$$
gN = \{gn\mid n \in N\}
$$

This is a (left) [**coset**]{style="color: blue"} of $N$ in $G$.

:::

::: {.callout-note icon="false"}
## Theorem

Let $\varphi \colon G \to H$ homomorphism with a kernal $K$. The set of cosets of $K$ in $G$ with operation $uK \star vK = (uv)K$ forms a group.

:::

::: {.callout-tip icon="false"}
## Proof

Let $X,Y \in G/K$, and $Z = XY \in G/K$. Then for some $a,b \in H$,
$$
X = \varphi^{-1}(a)\: Y = \varphi^{-1}(b)
$$

This implies $Z = \varphi^{-1}(ab)$. Let $u,v$ be representations of $X,Y$ respectivly. We want to show that $uv \in Z$. Which is only true If

$$
\varphi(uv) \in ab \leftrightarrow \varphi(u)\varphi(v) = ab
$$

Which is true! Thus by our previous proposition $Z = uvK$.
:::

You cannot define $G/N$ for any $N \leq G$. 

::: {.callout-note icon="false"}
## Theorem

You cannot define $G/N$ for any $N \leq G$. 

:::
::: {.callout-tip icon="false"}
## Proof

Let $\varphi \colon G \to H$ be a homomorphism with Kernal $K$. Then 

$$
gKg^{-1} \subseteq K \; \forall g \in G
$$

$\varphi(gkg^{-1}) = e$
:::

If we have a subgroup $N$ of $G such that $gNg^{-1} \subseteq N$ for all $g \in G$, then multiplication in $G/N$ is well defined.

::: {.callout-note icon="false"}
## Theorem

$$G/N \times G/N \rightarrow G/N
$$
$$(xN, xG)
$$
:::

::: {.callout-tip icon="false"}
## Proof

If $x_1N = x_2N, y_1N=y_2N$ then $x_1^{-1}x_2 \in N$ and $y_1^{-1}y_2 \in N$
:::

## Orbit stabalizers

Define
$$
b = g \cdot a \rightarrowtail gG_a
$$


::: {.callout-note icon="false"}
## Definition

The action of $G$ on $a$ is called [**transitive**]{style="color: blue"} if there is only one orbit
:::

::: {.callout-warning icon="false"}
## Example

$D_8$ acts transitivly on each of it's $4$ vertices.
:::

If $G$ acts trivially on $A$, then $G_a = G,\, \forall a \in A$. Then the orbits 

$$
orb(a) = \{b \mid b = g \cdot a \text{ for } g \in G\} = a.
$$ 

This is an example of a non-transitive action. If however

$$
G = S_n
$$

Then there always exists a $g \in G$ such that $a = g \cdot b$.

Let $(G,\diamond)$ be a group, and $A = G$. Define

$$
g \cdot a = g \diamond a
$$

then

$$
(1) g_2 \cdot (g_1 \cdot a) = g_2 g_1 a
$$

$$
e\cdot a = ea = a
$$

Let $G$ be a group such that $H \leq G$

$$
A = \{gH\mid g\in G\}
$$

Define $g \cdot aH = gaH$.

Suppose $A$ has $n$ elements

$$
a_1H \dots a_nH
$$

We can describe $\sigma_g$ as $\sigma_g(i) = j$ iff $ga_i = a_j$

::: {.callout-warning icon="false"}
## Example

Let $G = D_8$, and $H = \langle s \rangle$. Then

$$
A = \{eH,rH,r^2H,r^3H\}
$$

Label the four elements $1,2,3,4$ respectivly. We can compute $\sigma_s$

\begin{align*}
&s\cdot eH = sH = H\quad &\sigma_s(1) = 1\\
&s\cdot rH = srH = r^3H\quad &\sigma_s(2) = 4\\
&s\cdot r^2H = sr^2H = r^2H\quad &\sigma_s(3) = 3\\
&s\cdot r^3H = sr^3H = rH\quad &\sigma_s(4) = 2
\end{align*}

Thus $\sigma_s = (24)$. Similarly $\sigma_r(1234)$.
:::

::: {.callout-note icon="false"}
## Theorem

Let $G$ be a group $H \leq G$, $A = \{gh\mid g \in G\}$. Let $G$ act on $A$ by left multiplication.

- $G$ acts transitivly on $A$
- The stabalizer of $1H \in A$ in $G$ is $H$

:::

::: {.callout-tip icon="false"}
## Proof

$(1)$ Let $aH,bH$ be elements of $A$. Let $g = ba^{-1}$.

$$
g\cdot aH = gaH = ba^{-1}aH = bH
$$

Thus $orb(aH) = A$ so the group action is transitive. 

$(2)$ The stabalizer of $1H$ is

$$
\{g\in G \mid g \cdot 1H = 1H\} = \{g \in G \mid gH = H\} = H
$$

$(3)$ The kernal of the action

\begin{align*}
\ker(A) &=\{g \in G \mid gxH = xH \quad \forall x \in G\}\\
&= \{g \in G \mid x^{-1}gxH = H\quad \forall x \in G\}\\
&= \{g \in G \mid x^{-1}gx \in H \quad \forall x \in G\}\\
&= \{g \in G \mid g \in xHx^{-1} \quad x \in G\}\\
&= \bigcap_{x\in G} xHx^{-1}
\end{align*}

:::

::: {.callout-note icon="false"}
## Corollary

Every group is isomorphic to a subgroup of some symmetric group. If $|G| = n$ then $G$ is isomorphic to a subgroup of $S_n$.

:::

::: {.callout-tip icon="false"}
## Proof

Let $H = 1$. Take the permutation representatives

$$
\varphi \colon G \to S_g
$$

By the previous theorem, $\ker(\varphi)$ is contained in $H$, meaning $\ker(\varphi) = e$. By the first isomorphism theorem, 

$$
g \cong G/\ker(\varphi) \cong \text{im}(\varphi) \leq S_G
$$
:::

::: {.callout-note icon="false"}
## Corollary

If $G$ is a finite group of order $n$, and $p$ is the smallest prime dividing $n$, then any subgroup of index $p$ is normal.

:::

## Sylow theorem

Recall that Lagranges theorem tells you that the order of a subgroup divides the order of a group. This does not guarentee the existance of a subgroup $H_d$ for every divisor $d$ of a group. 

We start with the following Lemma.

::: {.callout-note icon="false"}
## Lemma

If $G$ is a finite abelian group, and $p$ is a prime dividing $|G|$ then $G$ contains an element of order $p$.
:::

::: {.callout-tip icon="false" collapse="true"}
## Proof

If $G$ is a finite abelian group, and $p$ is a prime dividing $|G|$ then $G$ contains an element of order $p$.

Use induction on $|G|$. We know that $x \not = e$. We have the base case $p = |G|$. Thus $\exists x, x^p = e$ by Lagranges theorem. Now suppose $p < |G|$.

If $p \mid |x|$, then $|x| = pn$ for some $n \in \mathbb{Z}$

$$
|x^n| = \frac{pn}{\gcd(n,pn)} = \frac{pn}{n} = p
$$

Thus $x$ has order $p$. If $p \not \mid |x|$, then let $\langle x \rangle = N$. Because $G$ is an abelian group, $N \trianglelefteq G$ since $N \not = \{e\}$,

$$
p \mid |G/N|
$$

Thus $G/N$ contains an element of order $p$. Using the induction hypothesis
$$
|y^p| = \frac{|y|}{p}
$$
:::

Now we get some tricky Definitions

::: {.callout-note icon="false"}
## Definition

Let $G$ be a group and $p$ be a prime. A group of order $p^\alpha$ for $\alpha \geq 0$ is called a [**p-group**]{style="color: blue"}. 

A subgroup of a $p$-group is called a [**p-subgroup**]{style="color: blue"}.

If $G$ is a group of order $mp^\alpha$ where $p \nmid m$, then a subgroup of order $p^\alpha$ is called a [**Sylow p-subgroup**]{style="color: blue"}
:::

Let $G$ be a group. The set of Sylow $p$-subgroups is denoted

$$
Syl_p(G)
$$

And the number of Sylow $p$-subgroups 

$$
n_p(G)
$$

Sylow had three major theorems in Abstract Algebra relating to these Sylow $p$-subgroups

::: {.callout-note icon="false"}
## Theorem (Sylow 1)

Let $G$ be a group of order $mp^\alpha$ where $p$ is a prime not dividing $m$, then there exists a Sylow $p$-subgroup.
:::

::: {.callout-note icon="false"}
## Theorem (Sylow 2)

If $P$ is a Sylow $p$-subgroup  of $G$ and $Q$ is any $p$-subgroup of $G$

$$
\exists g \in G \mid Q \leq gPg^{-1}
$$

In particular, any two Sylow $p$-subgroups are conjugate if $Q$ is a Sylow $p$-subgroup $\exists g$ such that $Q = gPg^{-1}$.
:::

::: {.callout-note icon="false"}
## Theorem (Sylow 3)

The number of Sylow $p$-subgroups of $G$ is of the form $1 + kp$, i.e.

$$
n_p(G) = 1 \mod p
$$

Futhermore, $n_p(G) = [G \colon N_g(p)]$ and $n_p(G) \mid m$.
:::

We need only prove the first theorem however.

::: {.callout-tip icon="false" collapse="true"}
## Proof (Sylow 1)

We start our proof using induction on $|G|$.

For our base case, if $|G| = 1$, there is nothing to prove. Assume (for the induction hypothesis), Sylow subgroups exist for all groups smaller than $|G|$. 

If $p \mid |Z(G)|$, by lemma $Z(G)$ has an element of order $p$ and thus a subgroup of order $p$. Call this subgroup $N$.

Let $\overline{G} = G/N$. Note

$$
\frac{|G|}{|N|} = \frac{p^{\alpha}m}{p} = \frac{p^{\alpha - 1}}{m}.
$$

So $|\overline{G}| = p^{\alpha - 1}m$. By the induction hypothesis, $\overline{G}$ has a subgroup of order $p^{\alpha + 1}$. Call this subgroup $\overline{P}$. By the correspondence isomorphism theorem, let $P$ be such that $P / N = \overline{P}$. Note

$$
|P| = |P/N| |N| = p^{\alpha - 1}p = p^{\alpha}
$$

So $P$ is a Sylow p-subgroup of $G$.

If $p\nmid{}|Z(G)|$, let $g_1\dots{}g_r$ be representatives of distinct, non-central congruancy classes of $G$. Then

$$
|G| = |Z(G)| + \sum\limits^r_{i=1}[G \colon C_G(g_i)]
$$

Note that 

$\forall i,\,p \mid [G \colon C_G(g_i)] \implies  p \mid \sum\limits^r_{i=1}[G \colon C_G(g_i)]$

Would imply $p \mid Z(G)$ which we know is false. So therefore there exists some $i$ such that $p \nmid [G \colon C_G(g_i)]$. For this $i$, let $H = C_g(g_i)$.

$$
[G \colon C_G(g_i)] = \frac{|G|}{|C_G(g_i)|} = \frac{|G|}{|H|}
$$

So $H = p^{\alpha}k$ for some $k$ such that $p \nmid k$. Since $g_i \not = Z(G)$, $C_G(g_i) \not = G$. Therefore $k < m$. Because $|H| < |G|$ by induction $H$ has a sylow $p$-subgroup $|p| = p^{\alpha}$, so $P$ is a Sylow $p$-subgroup of $G$.
:::