---
title: "Continuous Functions"
format:
  html:
    toc: true
    html-math-method: katex
---

::: {.callout-note icon="false"}
## Definition

Let $f \colon D \to \mathbb{R}$, where $x,c \in D$. We say that $f$ is [continuous at $c$]{.definition} if

$$
\forall \varepsilon > 0, \exists \delta > 0, |x-c| < \delta \implies |f(x) - f(c)| < \varepsilon.
$$

:::

In English, this means a function is continuous if $x$ approaching $c$ implies the difference between $f(x)$ and $f(c)$ is arbitrarily small.

If $f$ is continuous at all points $x \in D$, we say that $f$ is [continuous on $D$]{.definition}. Note that this definition of continuity is a pointwise notion.

::: {.callout-note icon="false"}
## Theorem 2.2.1

Let $f \colon D \to \mathbb{R}$ and let $c \in D$. Then the following three conditions are equivalent

$(a)$ $f$ is continuous at $c$.

$(b)$ If $(x_n)$ is any sequence in $D$ such that $(x_n)$ converges to $c$, then $\lim f(x_n) = f(c)$.

$(c)$ For every neighborhood $V$ of $f(c)$ there exists a neighborhood $U$ of $c$ such that $f(U \cap D) \subseteq V$.

Futhermore if $c$ is an accumulation point of $D$, then the above are all equivalent to 

$(d)$ $f$ has a limit at $c$ and $\lim_{x \to c} f(x) = f(c)$.

:::

::: {.callout-tip icon="false" collapse="true"}
## Proof 

We will assume the function is continuous at $c$, and show it implies the rest of the properties.

---------

$(a) \implies (c)$

Then there exists a neighborhood $U$ of $c$ such that $U \cap D = \{c\}$. It follows that, for any neighborhood $V$ of $f(c)$, $f(U \cap D) = \{f(c)\} \subseteq V$. Thus $(a)$ implies $(c)$.

:::

Taking the negation of $(a)$ and $(b)$ in this Theorem, we have a useful Corollary for what it means for a function to be discontinous.

::: {.callout-note icon="false"}
## Corollary 2.2.2

Let $f \colon D \to \mathbb{R}$ and $c \in D$. Then $f$ is discontinous at $c$ if and only if there exists a sequence $(x_n)$ in $D$ such that $(x_n)$ converges to $c$ but the sequence $(f(x_n))$ does not converge to $f(c)$.
:::

::: {.callout-tip icon="false" collapse="true"}
## Proof (TO-DO)

:::


::: {.callout-warning icon="false"}
## Example

Take the function $f \colon \mathbb{R} \to \mathbb{R}$ where

$$
f(x) =
\begin{cases}
1 \text{ if $x$ is rational}\\
0 \text{ if $x$ is irrational}
\end{cases}
$$

**Claim:** $f$ is discontinous at every real number.

For any point $c \in \mathbb{R}$, take the neighborhood $V$ of $f(c)$ with $\varepsilon < 1$. The neighborhood $U$ of $c$ will always contain both rational and irrational points (Due to both being dense in $\mathbb{R}$), such that $f(U \cap D) \not \subseteq V$. Thus by Theorem $2.2.1$, the function is not continous at $c$.

:::

::: {.callout-note icon="false"}
## Theorem 2.2.3 (Algebraic Relations of Continuity)

Let $f,g\; \colon D \to \mathbb{R}$ and $c \in D$. If $f,g$ are both continous at the point $c,$ then 

$(a)$ $f + g$ and $fg$ are continous at $c$, and

$(b)$ $f/g$ is continous at $c$ if $g(c) \not = 0$.

:::

::: {.callout-tip icon="false" collapse="true"}
## Proof (TO-DO)

Use convergence criterion and previous results.
:::

::: {.callout-note icon="false"}
## Theorem 2.2.4

Let $f \colon D \to \mathbb{R}$ and $g \colon E \to \mathbb{R}$ such that $f(D) \subseteq E$.

If $f$ is continuous at $c \in D$ and $g$ is continuous at $f(c)$, then $g \circ f \colon D \to \mathbb{R}$ is continuous at $c$.

:::

::: {.callout-tip icon="false" collapse="true"}
## Proof (TO-DO)

We want to show that given any neighborhood $V$ of $g(f(c))$, there exists a neighborhood $U$ of $c$ such that $f(U \cap D) \subseteq V$.

Since $g$ is continous at $f(c)$, we know that there exists a neighborhood $W$ of $f(c)$ such that $g(W \cap E) \subseteq V$. Similarly since $f$ is continous at $c$, there exists a neighborhood $U$ of $c$ such that $f(U \cap D) \subseteq W$. 

:::


::: {.callout-note icon="false"}
## Theorem 2.2.5

A function $f\colon D \to \mathbb{R}$ is continous on $D$ if and only if for every open set $U$ of $\mathbb{R}$, there exists an open subset $V$ of $\mathbb{R}$ such that $V \cap D = f^{-1}(U)$.

:::

::: {.callout-tip icon="false" collapse="true"}
## Proof (TO-DO)


**WTS:** $f$ being continous on $D$ implies $V \cap D = f^{-1}(u)$ .

Assume $f$ is continous on $D$. Let $U$ be an open subset of $\mathbb{R}$. If $c \in f^{-1}(U)$, then $f(c) \in U$. Since $U$ is open, there exists a neighborhood $U^\prime \subseteq U$ containing $f(c)$. Since $f$ is continous, there exists a neighborhood $V(c)$ of $c$ such that $f(V(c) \cap D) \subseteq U^\prime$.

Let $V = \bigcup_{c \in f^{-1}(u)}V(c)$. Now since $V(c)$ is open, we know $V$ is open and $V \cap D = f^{-1}(U)$. $\square$

**WTS:** $V \cap D = f^{-1}(u)$ implies that $f$ is continous on $D$.

:::

Note that the pre-image of a set may not exist. In this case we would say $f^{-1}(U)$ is the empty set, $\varnothing$.

$And when $D$ is $\mathbb{R}$, we can write

::: {.callout-note icon="false"}
## Corollary 2.2.6 

A function $f \colon \mathbb{R} \to \mathbb{R}$ is continuous if and only if $f^{-1}(G)$ is open in $\mathbb{R}$

:::


::: {.callout-tip icon="false" collapse="true"}
## Proof (TO-DO)

:::

## Practice

## Recap

In this section we proved

::: {.callout-note icon="false"}
## Theorem 2.2.1

Let $f \colon D \to \mathbb{R}$ and let $c \in D$. Then the following three conditions are equivalent

$(a)$ $f$ is continuous at $c$.

$(b)$ If $(x_n)$ is any sequence in $D$ such that $(x_n)$ converges to $c$, then $\lim f(x_n) = f(c)$.

$(c)$ For every neighborhood $V$ of $f(c)$ there exists a neighborhood $U$ of $c$ such that $f(U \cap D) \subseteq V$.

Futhermore if $c$ is an accumulation point of $D$, then the above are all equivalent to 

$(d)$ $f$ has a limit at $c$ and $\lim_{x \to c} f(x) = f(c)$.

:::

::: {.callout-note icon="false"}
## Corollary 2.2.2

Let $f \colon D \to \mathbb{R}$ and $c \in D$. Then $f$ is discontinous at $c$ if and only if there exists a sequence $(x_n)$ in $D$ such that $(x_n)$ converges to $c$ but the sequence $(f(x_n))$ does not converge to $f(c)$.
:::

::: {.callout-note icon="false"}
## Theorem 2.2.3 (Algebraic Relations of Continuity)

Let $f,g\; \colon D \to \mathbb{R}$ and $c \in D$. If $f,g$ are both continous at the point $c,$ then 

$(a)$ $f + g$ and $fg$ are continous at $c$, and

$(b)$ $f/g$ is continous at $c$ if $g(c) \not = 0$.

:::

::: {.callout-note icon="false"}
## Theorem 2.2.4

Let $f \colon D \to \mathbb{R}$ and $g \colon E \to \mathbb{R}$ such that $f(D) \subseteq E$.

If $f$ is continuous at $c \in D$ and $g$ is continuous at $f(c)$, then $g \circ f \colon D \to \mathbb{R}$ is continuous at $c$.

:::

::: {.callout-note icon="false"}
## Theorem 2.2.5

A function $f\colon D \to \mathbb{R}$ is continous on $D$ if and only if for every open set $U$ of $\mathbb{R}$, there exists an open subset $V$ of $\mathbb{R}$ such that $V \cap D = f^{-1}(U)$.

:::

::: {.callout-note icon="false"}
## Corollary 2.2.6 

A function $f \colon \mathbb{R} \to \mathbb{R}$ is continuous if and only if $f^{-1}(G)$ is open in $\mathbb{R}$

:::