project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "OOMN"
  description: "A college project"
  site-url: "https://orionjordan.github.io/"

  navbar:
    background: primary
    search: true
    left:
      - text: "Content"
        href: "./qmd/content/index.qmd"


  sidebar:
    - title: "graph"
      contents:
      - "./qmd/graph/GraphTheory.qmd"
      - section: "**Introduction**"
        contents:
        - "./qmd/graph/intro/graphs.qmd"

    - title: "integral"
      contents:
      - "./qmd/integral/intro.qmd"
      - section: "**Simple Techniques**"
        contents:
        - "./qmd/integral/simple/basics.qmd"
        - "./qmd/integral/simple/substitution.qmd"
        - "./qmd/integral/simple/intpart.qmd"
        - "./qmd/integral/simple/decomp.qmd"
        - "./qmd/integral/simple/trigsub.qmd"
      - section: "**Tricky Techniques**"
        contents:
        - "./qmd/integral/tricky/hyperbolic.qmd"

    - title: "Logic"
      contents:
      - "./qmd/logic/intro.qmd"
      - section: "**Formal systems**"
        contents:
        - "./qmd/logic/formal-systems/formal-language.qmd"

    - title: "Abstract Algebra"
      contents:
      - "./qmd/abstract/intro.qmd"
      - section: "**Introduction into Groups**"
        contents:
        - "./qmd/abstract/intro-to-groups/definitions.qmd"
        - "./qmd/abstract/intro-to-groups/symmetric-groups.qmd"
        - "./qmd/abstract/intro-to-groups/homo-iso.qmd"
        - "./qmd/abstract/intro-to-groups/subgroups.qmd"
      - section: "**Quotient Groups**"
        contents:
        - "./qmd/abstract/quotient-groups/quotient-group.qmd"

    - title: "Real Analysis"
      contents:
      - "./qmd/realanal/intro.qmd"
      - section: "Sequences"
        href: "./qmd/realanal/sequences.qmd"
        contents:
        - "./qmd/realanal/sequences/definition.qmd"
        - "./qmd/realanal/sequences/convergence.qmd"
        - "./qmd/realanal/sequences/limittheo.qmd"
        - "./qmd/realanal/sequences/mono-cauchy.qmd"
        - "./qmd/realanal/sequences/subsequences.qmd"
      - section: "Limits and Continuity"
        href: "./qmd/realanal/limits-cont.qmd"
        contents:
        - "./qmd/realanal/limits-cont/funclim.qmd"
        - "./qmd/realanal/limits-cont/cont-func.qmd"
        - "./qmd/realanal/limits-cont/cont-func-prop.qmd"
        - "./qmd/realanal/limits-cont/uniform-continuity.qmd"
      - section: "Differentiation"
        href: "./qmd/realanal/differentiation.qmd"
        contents:
        - "./qmd/realanal/differentiation/derivatives.qmd"
        - "./qmd/realanal/differentiation/mvt.qmd"
        - "./qmd/realanal/differentiation/lhospital.qmd"
        - "./qmd/realanal/differentiation/taylor.qmd"
      - section: "Integration"
        href: "./qmd/realanal/integration.qmd"
        contents:
        - "./qmd/realanal/integration/riemann.qmd"
        - "./qmd/realanal/integration/riemannprop.qmd"
        - "./qmd/realanal/integration/fundcalc.qmd"
      - section: "Infinite Series"
        href: "./qmd/realanal/infinite-series.qmd"
        contents:
        - "./qmd/realanal/infinite-series/converge.qmd"

theme:
  light: flatly
  dark: darkly

format:
  html:
    css: styles.css
    header-includes: |
      <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/gh/bitmaks/cm-web-fonts@latest/fonts.css">
    mainfont: 'Computer Modern Serif'
    fontsize: 14pt