project:
  type: website
  output-dir: docs

website:
  title: OOMN
  navbar:
    background: primary
    search: true
    left:
      - text: "Basics"
        file: "./qmd/basics/sets.qmd"
      - text: "Graph Theory"
        file: "./qmd/graph/GraphTheory.qmd"
      - text: "Integral"
        file: "./qmd/integral/intro.qmd"

  sidebar:
    - title: "basics"
      style: "floating"
      background: light
      contents:
      - section: "Basics"
        contents:
         - "./qmd/basics/sets.qmd"
         - "./qmd/basics/sets1.qmd"
         - "./qmd/basics/sets2.qmd"

    - title: "graph"
      contents:
      - "./qmd/graph/GraphTheory.qmd"
      - section: "**Introduction**"
        contents:
        - "./qmd/graph/intro/graphs.qmd"

    - title: "integral"
      contents:
      - "./qmd/integral/intro.qmd"
      - section: "**Simple Techniques**"
        contents:
        - "./qmd/integral/simple/basics.qmd"
        - "./qmd/integral/simple/substitution.qmd"
        - "./qmd/integral/simple/intpart.qmd"
      - section: "**Tricky Techniques**"
        contents:
        - "./qmd/integral/tricky/hyperbolic.qmd"



