---
title: "Substitution"
format:
  html:
    toc: true
    html-math-method: katex
---

The motivating example for this section will be the integral shown below.

$$
\int \sec^2(x)e^{1 + \tan{x}} \, dx
$$

The techniques shown in the last section don't work here. Linearity does not allow for separation of products, and we don't have an identity which gets us a solution. In order to solve these types of integrals, we'll need a new rule.

::: {.callout-warning icon="false"}
## Example (Substitution)

The integral can be rewrote if one makes the following substitution.

$$
u = 1 + \tan^2x
$$

Then computing the differential

$$
du = \sec^2x \,dx
$$

We can put these terms into the integral and obtain

$$
\int e^{u} \, du
$$

Which clearly evaluates to

$$
\int e^{u} \, du = e^u + C
$$

And then undoing the substitution

$$
\int \sec^2(x)e^{1 + \tan{x}} \, dx = e^{1+\tan x} + C
$$
:::

Substitution can often be thought of as undoing chain rule, by substituting the interior function.


::: {.callout-note icon="false"}
## Definition (Substitution rule)

The [substitution rule]{.definition} gives

$$
\int f(g(x))g^\prime(x)\, dx = \int f(u)\, du, \text{where } u = g(x).
$$
:::

The biggest problem is identitfying the function to substitute. There is no general way of identifying which function in the integrand needs to be substituted.

## Problems

This will be a large collection of problems, giving lots of examples for how we choose our substitutions to turn our integral back into an explicit form.

#### Integrals with Inverse power rule

::: {.callout-warning icon="false"}
## Problem 50

Evaluate the following integral
$$
\int (2x + 4)(x^2 + 4x + 3)^3 \, dx
$$
:::

::: {.callout-warning icon="false"}
## Problem 51

Evaluate the following integral
$$
\int (2x+3)\sqrt{x^2 + 3x} \, dx
$$
:::

::: {.callout-warning icon="false"}
## Problem 52

Evaluate the following integral
$$
\int \frac{3x^2}{(x^3 + 2)^{7/2}} \, dx
$$
:::

::: {.callout-warning icon="false"}
## Problem 53

Evaluate the following integral
$$
\int \frac{x}{\sqrt{1-2x^2}} \, dx
$$
:::

#### Integrals with Logarithms and Exponents

::: {.callout-warning icon="false"}
## Problem 54

Evaluate the following integral
$$
\int 2x \cos (x^2) e^{\sin (x^2)} \, dx
$$
:::

::: {.callout-warning icon="false"}
## Problem 55

Evaluate the following integral
$$
\int \frac{-3x^2}{e^{x^3 + 2}} \, dx
$$
:::

::: {.callout-warning icon="false"}
## Problem 56

Evaluate the following integral
$$
\int e^x e^{e^x} \, dx
$$
:::

::: {.callout-warning icon="false"}
## Problem 57

Evaluate the following integral
$$
\int \frac{x}{x^2 + a} \, dx
$$
:::

::: {.callout-warning icon="false"}
## Problem 58

Evaluate the following integral
$$
\int \frac{x^2}{x^3 + a} \, dx
$$
:::

::: {.callout-warning icon="false"}
## Problem 59

Evaluate the following integral
$$
\int \frac{1}{x \ln x} \, dx
$$
:::

::: {.callout-warning icon="false"}
## Problem 60

Evaluate the following integral
$$
\int \frac{e^x}{1 + e^x} \, dx
$$
:::

::: {.callout-warning icon="false"}
## Problem 61

Evaluate the following integral
$$
\int \frac{\sec^2 x}{1 + \tan x} \, dx
$$
:::


#### Integrals with Trigonometric Functions

::: {.callout-warning icon="false"}
## Problem 62

Evaluate the following integral
$$
\int x \sin x^2 \, dx
$$
:::

::: {.callout-warning icon="false"}
## Problem 63

Evaluate the following integral
$$
\int x \cos (x^2 + 1) \, dx
$$
:::

::: {.callout-warning icon="false"}
## Problem 64

Evaluate the following integral
$$
\int \tan x \, dx
$$
:::

::: {.callout-warning icon="false"}
## Problem 65

Evaluate the following integral
$$
\int \cot x \, dx
$$
:::

::: {.callout-warning icon="false"}
## Problem 66

Evaluate the following integral
$$
\int \sec x \, dx
$$
:::

::: {.callout-warning icon="false"}
## Problem 67

Evaluate the following integral
$$
\int \csc x \, dx
$$
:::

::: {.callout-warning icon="false"}
## Problem 68

Evaluate the following integral
$$
\int \frac{1}{x^2 + a^2} \, dx
$$
:::

::: {.callout-warning icon="false"}
## Problem 69

Evaluate the following integral
$$
\int \frac{1}{\sqrt{a^2 - x^2}} \, dx
$$
:::

::: {.callout-warning icon="false"}
## Problem 70

Evaluate the following integral
$$
\int \frac{1}{x\sqrt{x^2 - a^2}} \, dx
$$
:::

::: {.callout-warning icon="false"}
## Problem 71

Evaluate the following integral
$$
\int \frac{\arctan x}{x^2 + 1} \, dx
$$
:::

::: {.callout-warning icon="false"}
## Problem 72

Evaluate the following integral
$$
\int \frac{\arcsin x}{\sqrt{1 - x^2}} \, dx
$$
:::

::: {.callout-warning icon="false"}
## Problem 73

Evaluate the following integral
$$
\int \frac{\text{arcsec}\, x}{x\sqrt{x^2 - 1}} \, dx
$$
:::

::: {.callout-warning icon="false"}
## Problem 74

Evaluate the following integral
$$
\int \tanh x \, dx
$$
:::

::: {.callout-warning icon="false"}
## Problem 75

Evaluate the following integral
$$
\int \text{coth} \, x \, dx
$$
:::

::: {.callout-warning icon="false"}
## Problem 76

Evaluate the following integral
$$
\int \text{sech} \, x \, dx
$$
:::

::: {.callout-warning icon="false"}
## Problem 77

Evaluate the following integral
$$
\int \text{csch} \, x \, dx
$$
:::

::: {.callout-warning icon="false"}
## Problem 78

Evaluate the following integral
$$
\int \frac{e^x}{1 - e^{2x}} \, dx
$$
:::

## Special problems

::: {.callout-warning icon="false"}
## Problem 79 - Pauls Online Notes (Calculus - 5.3.1)

Evaluate the following integral

$$
\int   {{\left( {8x - 12} \right){{\left( {4{x^2} - 12x} \right)}^4}\,dx}}
$$

:::

::: {.callout-tip icon="false" collapse="true"}
## Solution

Using the substitution 

$$
u = 4x^2 - 12x
$$

We get
$$
\int   {{\left( {8x - 12} \right){{\left( {4{x^2} - 12x} \right)}^4}\,dx}} = \frac{1}{5}(4x^2 - 12x)^5 + C
$$

:::

::: {.callout-warning icon="false"}
## Problem 80 - Pauls Online Notes (Calculus - 5.3.2)

Evaluate the following integral

$$
\int{{3{t^{ - 4}}{{\left( {2 + 4{t^{ - 3}}} \right)}^{ - 7}}\,dt}}
$$

:::

::: {.callout-tip icon="false" collapse="true"}
## Solution

Using the substitution 

$$
u = 2 - 4t^{-3}
$$

We get
$$
\int{{3{t^{ - 4}}{{\left( {2 + 4{t^{ - 3}}} \right)}^{ - 7}}\,dt}} = \frac{1}{24}(2+4t^{-3})^{-6} + C
$$

:::

::: {.callout-warning icon="false"}
## Problem 81 - Pauls Online Notes (Calculus - 5.3.14)

Evaluate the following integral

$$
\int \frac{\csc x \cot c}{2- \csc x} \, dx
$$

:::

::: {.callout-tip icon="false" collapse="true"}
## Solution

First notice how $\csc x \cot x$ is the derivative of $-\csc x$. This leads us to try some form of $\csc x$ for $u$. I use

$$
u = 2 - \csc x
$$

Leading too
$$
\int \frac{\csc x \cot c}{2- \csc x} \, dx = - \int \frac{1}{u} \, du 
$$

Which is then

$$
\int \frac{\csc x \cot c}{2- \csc x} \, dx = \ln |u| + C = \ln |2 - \csc x| + C
$$

:::

::: {.callout-warning icon="false"}
## Problem 82 - Pauls Online Notes (Calculus - 5.3.13)

Evaluate the following integral

$$
\int{{10\sin \left( {2x} \right)\cos \left( {2x} \right)\sqrt {{{\cos }^2}\left( {2x} \right) - 5} \,dx}}
$$

:::

::: {.callout-tip icon="false" collapse="true"}
## Solution

While the integral looks incredibly complex, if we substitute the term inside the radical (the usual choice) we can start to break it down.

$$
u = \cos^2(2x) - 5
$$

Thus
$$
\int{{10\sin \left( {2x} \right)\cos \left( {2x} \right)\sqrt {{{\cos }^2}\left( {2x} \right) - 5} \,dx}} = -\frac{5}{2} \int \sqrt{u} \, du
$$

Which leads too

$$
\int{{10\sin \left( {2x} \right)\cos \left( {2x} \right)\sqrt {{{\cos }^2}\left( {2x} \right) - 5} \,dx}} = -\frac{5}{3}(\cos^2(2x) - 5)^\frac{3}{2} + C
$$

:::

::: {.callout-warning icon="false"}
## Problem 83 - Pauls Online Notes (Calculus - 5.4.6)

Evaluate the following integral

$$
\int{{20{{e}^{2 - 8w}}\sqrt {1 + {{e}}^{2 - 8w}}} \, + 7{w^3} - 6\,\,\sqrt[3]{w}\,dw}
$$

:::

::: {.callout-tip icon="false" collapse="true"}
## Solution

Using linearity on the integral allows us to do different substitutions. Seeing as the last two terms can be integrated with the inverse power rule, we only need to a substitution on the first term. Luckily this is an easy case.

$$
u = 1 + e^{2-8w}
$$

Gives

$$
\int{{20{{e}^{2 - 8w}}\sqrt {1 + {{e}}^{2 - 8w}}} \,dw} = -\frac{5}{2}\int \sqrt{u}\, du
$$

Which is

$$
\int{{20{{e}^{2 - 8w}}\sqrt {1 + {{e}}^{2 - 8w}}} \,dw} = -\frac{5}{3}(1 + e^{2-8w})^\frac{3}{2} + C
$$

Then solving the other terms gives us our solution.

$$
 = -\frac{5}{3}(1 + e^{2-8w})^\frac{3}{2} + \frac{7}{4}w^4 - \frac{9}{2}w^\frac{4}{3} + C
$$

:::

::: {.callout-warning icon="false"}
## Problem 84 - Pauls Online Notes (Calculus II - A7.1.18)

Evaluate the following integral

$$
\int{{\frac{{{x^7}}}{{\sqrt {{x^4} + 1} }}\,dx}}
$$

:::

::: {.callout-tip icon="false" collapse="true"}
## Solution

Using the substitution

$$
u = x^4 + 1
$$

We get

$$
\int{{\frac{{{x^7}}}{{\sqrt {{x^4} + 1} }}\,dx}} = \frac{1}{4}\int \frac{u - 1}{\sqrt{u}}
$$

Which we can then apply linearity and inverse power rule to, giving us

$$
\int{{\frac{{{x^7}}}{{\sqrt {{x^4} + 1} }}\,dx}} = \frac{1}{4}\left( \frac{2}{3}(x^4 + 1)^\frac{3}{2} + 2(x^4 + 1)^\frac{1}{2}\right) + C
$$
:::