---
title: "Base Number Arithmetic"
format:
  html:
    toc: true
    html-math-method: katex
---

Arithmetic in different bases works exactly the same, but takes some getting used to. It's easy to forget when to carry and make compounding mistakes.

# Addition

Addition in other bases works the exact same as base $10$. We could either add the numbers directly,

$$
21_6 + 14_6 = 25_6 + 10_6 = 35_6 
$$

Or convert to base 10 and preform our addition normally

$$
21_6 + 14_6 = 13_{10} + 10_{10} = 23_{10} = 35_6 
$$

# Subtraction

Subtraction unsuprisingly is no different. In the example below we seperate the number into groups of $9$.

\begin{align*} 
517_9 - 214_9 &= (5 - 2) \cdot 9^2 + (1 - 1) \cdot 9^1 + (7 - 4) \cdot 9^0\\
&= 3 \cdot 9^2 + 0 \cdot 9^1 + 3 \cdot 9^0\\
&= 303_9
\end{align*}

# Multiplication

When multiplying two numbers of any base, it is almost always easier to regroup the multiplicands into bundles.

\begin{align*} 

435_6 &= 4 \cdot 6^2 + 3 \cdot 6^1 + 5 \cdot 6^0\\
12_6 &=  0 \cdot 6^2 + 1 \cdot 6^1 + 2 \cdot 6^0
\end{align*}

We can then multiply the numbers using normal methods

$$
(4 \cdot 36 + 3 \cdot 6 + 5) \cdot (6 + 2) = \\
= 167 \cdot 8\\
= 1336
$$


# Division

The process of long division is the same in every base, so I won't waste your time with needless examples (I don't wanna Tex them).

# Problems

## Review

::: {.callout-warning icon="false"}
## Alcumus - Level 18 (#29673)

Find the positive base $b$ in which the equation $13\cdot15=243$ is valid.
:::

::: {.callout-tip icon="false" collapse="true"}
## Solution

By simply multiplying the equation out, we get a quadratic

$$
(b + 3)(b + 5) = 2b^2 + 4b + 3
$$

Simplifying to

$$
(b - 6)(b + 2) = 0
$$

Since $b$ must be positive, $b$ must be equal to $6$.
:::

## Challenge

::: {.callout-warning icon="false"}
## Alcumus - Level 23 (#29671)

If $S$, $H$, and $E$ are all distinct non-zero digits less than $5$ and the following is true, find the sum of the three values $S$, $H$, and $E$, expressing your answer in base $5$.

$$
\begin{array}{cccc} 
&S&H&E_5\\ 
&+&H&E_5\\ 
\hline &S&E&S_5\\ 
\end{array}
$$

:::

::: {.callout-tip icon="false" collapse="true"}
## Solution

Removing the leftmost digit gives us 

$$
\begin{array}{cccc} 
&&H&E_5\\ 
&+&H&E_5\\ 
\hline &&E&S_5\\ 
\end{array}
$$

Assuming there is no carry on the rightmost digit, we have $S = 2E$ and $E = 2H$. After some algebra we arrive at $S = 4, H = 1, E = 2$. Thus we have the sum $12_5$
:::