---
title: "Basis for a Topology"
format:
  html:
    toc: true
    html-math-method: katex
---

Previously we defined a topology by specifying the entire set of open sets. However, we could save some time by only specifying a few open sets and using our properties of open sets (arbitrary unions for example) to infer what else constitutes an open set.

<!-->
TO:DO Example of specifying as few open sets as possible.
<--->

::: {.callout-note icon="false"}
## Definition

If $X$ is a set, a [basis]{.definition} on $X$ is a collection $\mathscr{B}$ of subsets $B \subset X$ such that

($1$) For all $x \in X$, there exists some basis element $B$ containing $X$.

($2$) If $x$ belongs to two separate basis elements, $B_1,B_2$, then there exist some $B_3$ such that $x$ is in $B_3$ and ${B_3 \subset B_1 \cap B_2}$.

:::

<!-->
Why?
<--->

We can use a basis on a set to generate a topology on that set, by taking the following definition.

::: {.callout-note icon="false"}
## Definition

Let $X$ be a set and $\mathscr{B}$ a basis on $X$. Let $\mathcal{T}$ be the collection of subsets $U \subset X$ such that for each $x \in U$, there exists $B \in \mathcal{B}$ such $x \in B \subset U$.

Then the collection $\mathcal{T}$ is a topology, and is called the [topology generated by $\mathcal{B}$]{.definition}.
:::

Despite calling $\mathcal{T}$ a topology, we have not yet proven that fact.

::: {.callout-note icon="false"}
## Lemma
Given a set $X$ and a basis $\mathcal{B}$ on $X$, the collection generated by $\mathcal{B}$ is a topology. 
:::

::: {.callout-tip icon="false" collapse="true"}
## Proof

We have to show that the collection $\mathcal{T}$ generated by $\mathcal{B}$ is a topology, meaning we have to show it abides the three properties of a topology:

- The empty set $\varnothing$ and the set itself $X$ are in $\mathcal{T}$.

If $U$ is the empty set, then $U$ is open vacously. If $U$ is $X$, then for each $x \in X$, there exists some basis element containing $x$ and a subset of $X$ by definition. 

- Any union of elements in $\mathcal{T}$ is in $\mathcal{T}$.

We now must show than any indexed family $\{U_\alpha\}_{\alpha \in J}$ of elements in $\mathcal{T}$ has a union such that

$$
U = \bigcup_{\alpha \in J}U_{\alpha}
$$

is an element of $\mathcal{T}$. Given any $x \in U$, there is some index $\alpha$ such that $x \in U_\alpha$. Since $U_\alpha$ is open, there is a basis element $B$ such that $x \in B$ and $B \subset U_a \subset U$. Therefore $U$ is an element of $\mathcal{T}$.

- Any finite intersection of elements in $\mathcal{T}$ is in $\mathcal{T}$.

Now, given any $U_1,U_2$ we must show $U_1 \cap U_2$ is an element of $\mathcal{T}$. Given $x \in U_1 \cap U_2$, there exist $B_1 \subset U_1$ and $B_2 \subset U_2$ both containing $x$. By the definition of a basis, there exist some $B_3 \subset B_1 \cap B_2$ containing $x$. Then $x \in B_3$ and $B_3 \subset U_1 \cap U_2$, and therefore $U_1 \cap U_2$ is an element of $\mathcal{T}$.

By induction, one can clearly see that this holds for any finite amount of intersections.
:::

There is another way to construct a topology from a given basis.

::: {.callout-note icon="false"}
## Lemma
Let $X$ be a set and $\mathcal{B}$ be a basis for a topology $\mathcal{T}$ on $X$. Then $\mathcal{T}$ equals the collection of all unions of elements of $\mathcal{B}$. 
:::

::: {.callout-tip icon="false" collapse="true"}
## Proof

Any subset $B$ of $\mathcal{B}$ is an element of $\mathcal{T}$. Because $\mathcal{T}$ is a topology, any arbitrary union of elements in $\mathcal{B}$ are in $\mathcal{T}$.

We now must show that each element of $\mathcal{T}$ is a union of basis elements. Given any $U \in \mathcal{T}$, for each element $x \in U$, there exists $B_x \in \mathcal{B}$ such that $x \in B_x \subset U$ by the definition of a basis. Then $U = \bigcup_{x \in U}B_x$, so $U$ is a union of elements of $\mathcal{B}$.  
:::

Now we have two ways to create a topology given a basis. Now we examine creating a basis from a topology.

::: {.callout-note icon="false"}
## Lemma
Let $X$ be a set and $\mathcal{T}$ be a topology on $X$. Suppose that $\mathcal{C}$ is a collection of open sets of $X$ such that for each $U$ in $\mathcal{T}$ and each $x \in U$, there exists some $C \in \mathcal{C}$ such that ${x \in C \subset U}$. Then $\mathcal{C}$ is a basis for $\mathcal{T}$.
:::

::: {.callout-tip icon="false" collapse="true"}
## Proof

We must first show $\mathcal{C}$ is a basis.

- For each $x \in X$, there is at least one basis element $B$ containing $x$.

We know $X$ is an open set in $\mathcal{T}$ by the definition of a topology on a set. Thus, for each $x \in X$, by our hypothesis there exists some $C \in \mathcal{C}$ such that ${x \in C}$.

- If $x$ belongs to two separate basis elements, $B_1,B_2$, then there exist some $B_3$ such that $x$ is in $B_3$ and ${B_3 \subset B_1 \cap B_2}$.

Let $x$ be an element of $C_1 \cap C_2$ where $C_1,C_2$ are basis elements of $\mathcal{C}$. Since $C_1 \cap C_2$ is an open set in $\mathcal{T}$, ny our hypothesis there exists $C_3$ such that $x \in C_3 \subset C_1 \cap C_2$.

Now we must show that the topology generated by $\mathcal{C}$, denoted $\mathcal{T}^\prime$, is the same as the topology $\mathcal{T}$. We do this by subset inclusion. This means we must show

-  $\mathcal{T} \subset \mathcal{T}^\prime$

For each $U \in \mathcal{T}$, and each $x \in U$, there exists some $C \in \mathcal{C}$ by hypothesis such that $x \in C \subset U$. Then it follows that $U \in \mathcal{T}^\prime$.

- $\mathcal{T}^\prime \subset \mathcal{T}$

For each $W \in \mathcal{T}^\prime$, we have that $W$ is a union of elements of $\mathcal{C}$. Since every element in $\mathcal{C}$ is also an element of $\mathcal{T}$, it follows that $W \in \mathcal{T}$.

Thus we have that $\mathcal{T} = \mathcal{T}^\prime$, and $\mathcal{C}$ forms a basis for $\mathcal{T}$.
:::

When topologies are given by bases, we use the following lemma to determine whether one topology is finer than another

::: {.callout-note icon="false"}
## Lemma
Let $\mathcal{B}$ and $\mathcal{B}^\prime$ be bases for the topologies $\mathcal{T}$ and $\mathcal{T}^\prime$ respectively, on a set $X$. Then the following are equivalent.

$(1)$ $\mathcal{T}^\prime$ is finer than $\mathcal{T}$.

$(2)$ For each $x \in X$ and each basis element $B \in \mathcal{B}$, there exist $B^\prime \in \mathcal{B}^\prime$ such that $x \in B^\prime \subset B$.
:::

::: {.callout-tip icon="false" collapse="true"}
## Proof

To show the two are equivalent, we must show that $(1) \implies (2)$, and that $(2) \implies (1)$.

 - $(2) \implies (1)$

 Given $U \in \mathcal{T}$, we want to show that $U \in \mathcal{T}^\prime$. By hypothesis we have that for all $x \in U$, there exists some $B \in \mathcal{B}$ such that $x \in B \subset U$. By condition $(2)$ we have that there exists some $B^\prime \in \mathcal{B}^\prime$ such that $x \in B^\prime \subset B \subset U$. Therefore $U \in \mathcal{T}^\prime$.

  - $(1) \implies (2)$

Let $x$ be an element of $X$ and $B \in \mathcal{B}$ such that $x \in B$. We have by $(1)$ that $\mathcal{T} \subset \mathcal{T}^\prime$, and thus $B \in \mathcal{T}^\prime$. Then since $\mathcal{T}^\prime$ is generated by $\mathcal{B}^\prime$, there exists some $B^\prime \in \mathcal{B}^\prime$ such that $x \in B^\prime \subset B$.

And therefore the two statements are equivalent.
:::

We can now use basies to generate some interesting topologies on the real line.

::: {.callout-note icon="false"}
## Definition

If $\mathcal{B}$ is a subset of $\mathbb{R}$ consisting of all open intervals

$$
(a,b) = \{x \in a < x < b\}
$$

the topology generated by $\mathcal{B}$ is called the [standard topology]{.definition} on the real line.
:::

We may also create a topology on some set by partitioning it, and then taking finite intersections and arbitrary unions of that set.

::: {.callout-note icon="false"}
## Definition

A [subbasis]{.definition} $\mathcal{S}$ for a topology on $X$ is a collection of subsets of $X$ whose union equals $X$.

The [topology generated by a subbasis]{.definition} $\mathcal{S}$ is the collection $\mathcal{T}$ of all unions of finite intersections of elements of $\mathcal{S}$.
:::