---
title: "Blumberg Theorem"
format:
  html:
    toc: true
    html-math-method: katex
---

## Motivation

It is immediately obvious that not every function $f\colon \mathbb{R} \to \mathbb{R}$, is continuous. However we can usually restrict the domain to remove any discontinuies. Even a function such as the Dirchlet function $\chi_\mathbb{Q}$ can be restricted $f \restriction \mathbb{Q}$ to create a continuous function.

Henry Blumberg proved in 1922 that for every function $f \colon \mathbb{R} \to \mathbb{R}$ there exists a domain $D$ such that $f$ can be restricted to a continuous function.

This set $D$ must be 'big' in some way to be interesting. Every function $f\colon \mathbb{R} \to \mathbb{R}$ is continuous when restricted to $\varnothing$, or to some finite subset of $\mathbb{R}$.

## Theorem



::: {.callout-note icon="false"}
## Theorem (Blumbergs Theorem)

For every $f \colon \mathbb{R} \to \mathbb{R}$ there exists a dense subset $D$ of $\mathbb{R}$ such that $f \restriction D$ is continuous.
:::


## Pleasant functions

::: {.callout-note icon="false"}
## Definition 

A function $f \colon \mathbb{R} \to \mathbb{R}$ is said to be f-[pleasant]{.definition} if for every open interval $I$ such that $f(x) \in I$, there exists an open interval $J^I_x$ such that $x \in J^I_x$ such that the set $f^{-1}(B)$ is dense in $J^I_x$.
:::
