---
title: "Points"
format:
  html:
    toc: true
    html-math-method: katex
---

While it is true that every topological property can be stated in open sets, it is often useful to talk about collections of points in a subset that have specific properties.

## Interior points

Interior points have similar properties to open sets.

::: {.callout-note icon="false"}
## Definition

Given a subset $S \subseteq \mathbb{R}$, a point $p \in S$ is an [interior point]{.definition} if there exists some $\varepsilon > 0$ such that 

$$
(p - \varepsilon, p + \varepsilon) \subset S.
$$
:::

It is clear that every point in an open set is an interior point, but interior points may exist in any number of sets.

::: {.callout-warning icon="false" collapse="true"}
## Example 

Let $A = [0,1]$. The point $p = 1/2$ is an interior point as there exists many epsilon, say $\varepsilon = 1/4$ for example, such that $(p - \varepsilon,p+\varepsilon) \subset A$.

The point $p = 1$ is not an interior point, as any epsilon will have $p + \varepsilon > 1$.  
:::

::: {.callout-note icon="false"}
## Theorem 

Let $S \in \mathbb{R}$. Then $S$ is open if and only if every point is an interior point.
:::

Say we had a closed set $B$ and we wanted to find the largest opn subset of it. For this we can define a new operation using interior points.

::: {.callout-note icon="false"}
## Definition

Let $S \subseteq \mathbb{R}$. The [interior]{.definition} of $S$ is the set containing all interior points of $S$, denoted $S^\mathrm{o}$.

:::

::: {.callout-warning icon="false" collapse="true"}
## Example 

Let $A = [0,1]$. We know every point in $(0,1)$ is an interior point of $A$, and $0,1$ are not interior points. Thus $A^\mathrm{o} = (a,b)$.
:::

It is rather obvious, but we should note that the interior of any set will always be open. It is perhaps not obvious that the interior of a set is the largest open subset of said set.

::: {.callout-note icon="false"}
## Theorem 

Let $S \subseteq \mathbb{R}$. Then $S^\mathrm{o}$ is the largest open subset of $S$.
:::

## Isolated points

::: {.callout-note icon="false"}
## Definition

Let $S \subseteq \mathbb{R}$, a point $p \in S$ is an [isolated point]{.definition} if there exists some $\varepsilon > 0$ such that $p$ is the only point is $S$ that belongs in the interval $(p - \varepsilon,p+\varepsilon)$.
:::

::: {.callout-warning icon="false" collapse="true"}
## Example 

Let $A = [0,1] \cup \{3\}$. Then $3$ is an isolated point because when $\varepsilon = 1$, $3$ is the only element in $A$ also in the interval $(p-1,p+1) = (2,4)$
:::

## Boundary points

::: {.callout-note icon="false"}
## Definition

Let $S \subseteq \mathbb{R}$, a point $p \in \mathbb{R}$ is an [boundary point]{.definition} if for all $\varepsilon > 0$, $(p - \varepsilon,p+\varepsilon)$ contains elements both inside and outside of $S$.
:::

::: {.callout-warning icon="false" collapse="true"}
## Example 

Let $A = [a,b]$. Then the points $a,b$ are both boundary points of $A$, since every interval is going to contain points both inside and outside of $A$.
:::

## Accumulation points

::: {.callout-note icon="false"}
## Definition

Let $S \subseteq \mathbb{R}$, a point $p \in \mathbb{R}$ is an [accumulation point]{.definition} if for all  $\varepsilon > 0$, $(p - \varepsilon,p+\varepsilon)$ contains some element $p_2 \in A$ such that $p_2 \not = p$.
:::

::: {.callout-warning icon="false" collapse="true"}
## Example 

Let $A = (a,b)$. Then the collection of all accumulation points of $A$ is the interval $[a,b]$.
:::


