---
title: "Homomorphisms and Isomorphisms"
format:
  html:
    toc: true
    html-math-method: katex
---

In this section we define what it means for two groups to be equivalent, i.e. have the same group-theoretic structure.

## Definitions

::: {.callout-note icon="false"}
## Definition

Let $(G,\star)$ and $(H,\diamond)$ be groups. 

Given a map $\varphi \colon G \to H$, if we can show that 

$$
\forall x,y \in G,\, \varphi (x \star y) = \varphi (x) \diamond \varphi(y)
$$

Then $\varphi$ is a [**homomorphism**]{style="color: blue"}
:::

One can think of a homomorphism as a map of sets that respect the group operations. When group operations are not specified, we often abbreviate

$$
\varphi(xy) = \varphi(x)\varphi(y)
$$

Where the LHS is the $G$ operation, and the RHS is the operation in $H$.

::: {.callout-note icon="false"}
## Definition

The map

$$
\varphi \colon G \to H
$$

is an [**Isomorphisms**]{style="color: blue"} if $\varphi$ is both a homomorphism, and a bijection. 
:::

If two groups are isomorphic, they are essentially the same. Every property satisfied by $G$ will be satisifed by $H$. If two groups are isomorphic, they are denoted

$$
G \cong H
$$

A homomorphism from a group to itself is called an [**endomorphism**]{style="color: blue"}, and an isomorphism from a group to itself is called an [**automorphism**]{style="color: blue"}.

::: {.callout-warning icon="false"}
## Example

Take the map $\varphi$ such that

$$
\varphi \colon (\mathbb{Z},+) \to (\mathbb{Z}/m\mathbb{Z}, +)
$$

$$
x \rightarrowtail [x]
$$

We can prove $\varphi$ to be a homomorphism, as

$$
\varphi (x+y) = [x + y]
$$

$$
\varphi (x) + \varphi (y) = [x] + [y] = [x + y]
$$

But not an isomorphism, as the function is not injective.
:::

::: {.callout-warning icon="false"}
## Example

For any group $G$, the identity map 

$$
G \rightarrow G
$$

$$
x \rightarrowtail x
$$

is an isomorphism, and an automorphism.
:::

::: {.callout-warning icon="false"}
## Example

For any groups $G,H$, the map $\varphi$ 

$$
\varphi \colon G \rightarrow H
$$

$$
g \rightarrowtail e_H
$$

is called the trivial homomorphism. As 

$$
\varphi(g_1g_2) = e_H
$$

$$
\varphi (g_1)\varphi (g_2) = e_He_H = e_H
$$
:::

## Properties of morphisms

Now we can be to look at some of the properties of homomorphisms and Isomorphisms.

::: {.callout-note icon="false"}
## Proposition 1.2.1

Let the following be groups
$$
(G, \star) \quad (H, \diamond) \quad (M, \square).
$$

And the following maps be homomorphisms

$$
f \colon G \rightarrow H,\quad g \colon H \rightarrow M
$$

Then

$$
g \circ f \colon G \rightarrow M
$$

is a homomorphism.

:::

::: {.callout-tip icon="false" collapse="true"}
## Proof

The proof is just a few lines of algebra

\begin{align*}
g(f(x \star y)) &= g(f(x) \diamond f(y))\\
&= g(f(x))\, \square \,g(f(y)))
\end{align*}
:::

Additionally

::: {.callout-note icon="false"}
## Proposition 1.2.2

Let

$$
\varphi \colon G \rightarrow H
$$

be a homomorphism. Let $e_H,e_G$ be the identity of $H$ and $G$ respectivly. Then

$$
\varphi(e_G) = e_H
$$

:::

::: {.callout-tip icon="false" collapse="true"}
## Proof

By algebra

\begin{align*}
e_G &= e_Ge_G\\
\varphi(e_G) = \varphi&(e_Ge_G) = \varphi(e_G)\varphi(e_G)\\
(\varphi(e_G))^{-1}\varphi(e_G) &= (\varphi(e_G))^{-1}\varphi(e_G)\varphi(e_G)\\
e_H &= e_H\varphi(e_G)\\
e_H &= \varphi(e_G)
\end{align*}
:::

::: {.callout-note icon="false"}
## Proposition 1.2.3

If $\varphi \colon G \rightarrow H$ is an isomorphism, then

- The cardinality of $G$ and $H$ are equivalent
- $H$ is abelian if and only if $G$ is abelian
- For all $x$ in $G$, the order of $x$ is the order of $\varphi(x)$
:::

This porposition lists some of the properties preserved under isomorphism. The proof requires the use of the following Lemma

::: {.callout-note icon="false"}
## Lemma 1.2.4

Let $\varphi \colon G \rightarrow H$ be a homomorphism. Then 

$$
\varphi(x^n) = \varphi(x)^n \quad \forall n \in \mathbb{Z}
$$
:::

::: {.callout-tip icon="false" collapse="true"}
## Proof

We use a proof by induction. When $n = 1$

\begin{align*}
\varphi(x^1) = \varphi(x)^1
\end{align*}

When $n > 1$

\begin{align*}
\varphi(x^{n-1}x) &= \varphi(x)^{n-1}\varphi(x)\\
\varphi(x^{n}) &= \varphi(x)^{n}
\end{align*}

:::

Now to prove Proposition $1.2.3$.

::: {.callout-tip icon="false" collapse="true"}
## Proof (FINISH)

$(1)$ Isomorphisms are bijections, and by the Schröder–Bernstein theorem, bijections preserve cardinailty.

$(2)$ Let $(G,\star)$ and $(H, \diamond)$ be groups. If $(G,\star)$ is abelian, and ${\varphi(a)=x},{\varphi(b)=y}$, then

\begin{align*}
x \diamond y &= \varphi(a) \diamond \varphi(b)\\
&= \varphi(a \star b)\\
&= \varphi(b \star a)\\
&= \varphi(b) \diamond \varphi(a)\\
&= y \diamond x
\end{align*}

$(3)$ We have three cases for this proposition

**Case 1:**

Suppose $|x| = n$ is finite and $|\varphi(x)|$ is infinite. Then

$$
\varphi(x)^n = \varphi(x^n) = \varphi(e_G) = e_H
$$

Thus $\varphi(x)$ has finite order $n$, a contradiction.

**Case 2:**

Suppose $|x|$ is infinite and $|\varphi(x)| = n$ is finite. Then

$$
\varphi (x^n) = \varphi (x)^n = e_H = \varphi(e_G)
$$

Because we have an isomorphism, $\varphi$ is injective, meaning

$$
x^n = e_G.
$$

Thus $|x|$ has finite order $n$, a contradiction.

**Case 3:**

Suppose $|x| = n$, $|\varphi(x)| = m$. Then

$$
\varphi(x)^n = \varphi(x^n) = \varphi(e_G) = e_H \implies m \leq n.
$$

Similarly,

$$
\varphi (e_G)= e_H = \varphi (x)^m = \varphi(x^m) \implies m \geq n
$$

Thus 

$$
m = n
$$
:::

Determining if two groups are isomorphic is an $NP$ problem, so it can take a while to prove.    


::: {.callout-tip icon="false" collapse="true"}
## Proof (FINISH)

Lets take the following groups $S_3$ and $\mathbb{Z}/6\mathbb{Z}$. There does not exist an isomorphism between these two, as $S_3$ is abelian, and $\mathbb{Z}/6\mathbb{Z}$ is not. Thus

$$
S_3 \not \cong \mathbb{Z}/6\mathbb{Z}
$$

There is however, an isomorphism between $D_6$ and $S_3$.

Let 

$$
D_6 = \{r,s \mid r^3 = s^2 = 1, sr = r^{-1}s\}
$$

We can map

$$
S_3 \rightarrow D_6
$$

$$
(1\,2\,3) \rightarrowtail r
$$

$$
(1\,2) \rightarrowtail s
$$

Which maps the generators to each other. Thus

$$
D_6 \cong S_3
$$

:::



