---
title: "Subsets and Subgroups"
format:
  html:
    toc: true
    html-math-method: katex
---

::: {.callout-note icon="false"}
## Definition

Let $(G,\star)$ be a group. 

$(H,\star)$ is a [**subgroup**]{.definition} of $(G,\star)$ if

$(1)$ $(H,\star)$ is a group

$(2)$ $H$ is a subset of $G$.

This is notated $H \leq G$.
:::

::: {.callout-note icon="false"}
## Definition

Let $G$ be a group, and $H$ be a subgroup of $G$. The subgroup $H = G$ itself is the [**improper**]{.definition} subgroup. All other subgroups are [**proper**]{.definition}. 
:::

::: {.callout-note icon="false"}
## Definition

Let $G$ be a group. The subgroup $\{e_G\}$ is the [**trivial**]{.definition} subgroup. All other subgroups are [**nontrivial**]{.definition}.
:::


::: {.callout-note icon="false"}
## Theorem

A subset $H$ of a closed group $G$ is a subgroup of $G$ if and only if

$(1)$ H is closed under the binary operation of $G$

$(2)$ The identity $e_G$ is in $H$

$(3)$ For all $a \in H$, $a^{-1} \in H$.
:::

::: {.callout-note icon="false"}
## Theorem

Let $H$ be a finite nonempty subset
:::

## Cyclic Subgroups

::: {.callout-note icon="false"}
## Theorem

Let $G$ be a group and let $a \in G$. Then

$$
H = \{a^n \mid n \in \mathbb{Z}\}
$$

is a subgroup of $G$ and is the smallest subgroup of $G$ that contains $a$. Furthermore, every subgroup containing $a$ contains $H$.
:::

::: {.callout-note icon="false"}
## Definition

Let $G$ be a group and let $a \in G$. Then the subgroup above is known as the cyclic subgroup of $G$ generated by $a$.
:::

::: {.callout-note icon="false"}
## Definition

A group $G$ is cyclic if and only if there exist some $a$ such that $\langle a\rangle = G$. 
:::

::: {.callout-note icon="false"}
## Theorem

Every cyclic group is abelian
:::

::: {.callout-tip icon="false" collapse="true"}
## Proof

Let $G$ be a cyclic group and let $a$ generate $G$.

If $g_1$ and $g_2$ are any two elements of $G$, there exists integers $r$ and $s$ such that $g_1 = a^r$ and $g_2 = a^s$. Then

$$
g_1g_2 = a^ra^s = a^{r+s} = a^{s+r} = a^sa^r = g_2g_1.
$$

So $G$ is abelian. 
:::

::: {.callout-note icon="false"}
## Theorem (Division Algorithm for $\mathbb{Z}$)

Let $m$ be a positive integer and $n$ be any integer. There exists integers $q,r$ sich that

$$
n = mq + r \quad\text{and}\quad 0 \leq r < m.
$$
:::

::: {.callout-note icon="false"}
## Theorem

A subset of a cyclic group is cyclic.
:::

::: {.callout-tip icon="false" collapse="true"}
## Proof

Let $G$ be a cyclic group generated by $a$ and let $H$ be a subgroup of $G$.
:::