---
title: "Axioms"
format:
  html:
    toc: true
    html-math-method: katex
---

The ideas we have studied up to now feel very natural, and are all true properties we want set theory to have. We want, however, for set theory to be built on absolute solid foundations with no ambiguity, and thus it is axiomatized in first order logic.

The following chapter is devoted to developing all the ideas from the last, with care for the Axioms. The specific axoioms we choose to include develop a system known as $ZFC$. This is not the only way to formalize set theory however, and not even the only set of axioms used to formalize $ZFC$.

The goal of this section is to start with two primitive notions, an object called a _set_, and a relation called _contains_, denoted with $\in$, and build up the usual $9$ axioms of $ZFC$.

## Basic Axioms

Formally we know nothing about what a set is or what the relation _containment_ does. We have our intuitive ideas of course, and need to somehow make explicit all of our assumptions. Lets start with a basic axiom, and see how it fits our intuition.

We may start with the simple axiom

::: {.callout-important icon="false"}
## Set Existence Axiom

There exist a set:

$$
\exists A (A = A)
$$
:::

::: {.callout-important icon="false"}
## Axiom of Extensionality.

If two sets have the same members, they are equal:

$$
\forall y \forall z \left[\forall x (x \in y \iff x \in z) \implies y = z\right]
$$
:::

The following axioms ensure the existence of many fundamental sets.

::: {.callout-important icon="false"}
## Empty Set Axiom

There is a set with no members:

$$
\exists A \forall x, x \not \in A
$$
:::

::: {.callout-note icon="false"}
## Proposition

There exists only one set to which no elements belong. Symbollically

$$
\forall A \forall B [(\forall u(u\not\in A) \land \forall v(v \not\in B)) \implies A = B]
$$
:::

::: {.callout-note icon="false"}
## Definition

Let $\varnothing$ be the set with no members. This is called the [empty set]{.definition}.
:::

Now we know for certain that at least one set exists. The following axioms will allow us to construct more sets from that.

## Existence Axioms

::: {.callout-important icon="false"}
## Pairing Axiom

For any two sets $A$ and $B$, there is a set having as members just $A$ and $B$:

$$
\forall u \forall v \exists B \forall x (x \in B \iff x = u \lor x = v)
$$
:::

This is our first method of constructing a new set from previous sets. 

::: {.callout-warning icon="false"}
## Example

Let $A$ and $B$ be sets. Then the set $\{A,B\}$ exists. Within our current universe of sets we have only shown the existence of $\varnothing$ as a set, but now, through the axiom of pairing, we can create $\{\varnothing,\varnothing\}$ which through the axiom of extension is equivalent too $\{\varnothing\}$.

We can apply this axiom repeatedly to create new sets.
:::

Next we look at a weak form of the Union Axiom which allows us to union two sets together.

::: {.callout-important icon="false"}
## Union Axiom (weak form)

For any two sets $a$ and $b$, there is a set having whose members are the elements of $a$ or $b$:

$$
\forall a \forall b \exists B \forall x (x \in B \iff x \in a \lor x \in b)
$$
:::

::: {.callout-warning icon="false"}
## Example

The axiom of pairing allowed us to construct sets with one element, and sets with two elements. Using the axiom of union, we are able to construct sets of any arbitrary length. For example, let $A,B,C$ be sets, then

$$
\{A\} \cup \{B,C\} = \{A,B,C\}.
$$

:::

::: {.callout-important icon="false"}
## Power Set Axiom

For any set $a$, there is a set whose members are exactly the subsets of $a$:

$$
\forall a \exists B \forall x (x \in B \iff x \subseteq a)
$$
:::

Now we can prove some facts



## Number construction

::: {.callout-note icon="false"}
## Definition

Let $S$ be a function known as the [successor]{.definition} function, defined by

$$
S(a) = a \cup \{a\}.
$$

where $a$ is a set.
:::

Then we can construct our numbers by repeatedly applying the successor function to the empty set.

$$
\begin{align*}
0 &= \{\} &=& \varnothing\\
1 &= \{0\} &=& \{\varnothing\}\\
2 &= \{0,1\} &=& \{\varnothing, \{\varnothing\}\}\\
3 &= \{0,1,2\} &=& \{\varnothing, \{\varnothing\},\{\{\varnothing, \{\varnothing\}\}\}\}
\end{align*}
$$