---
title: "The Empty Set"
format:
  html:
    toc: true
    html-math-method: katex
---

With the axioms of extension and specification, we can begin to construct some basic set theory!

## Existence of the Empty Set

We have mentioned some axioms, but have yet to show explicitly that any set at all exists. We wish to fix that here by constructing the empty set. 

This is usually accomplished in one of three ways[^1].

The first approach is to introduce an empty set axiom. Very often in books on set theory[^2] the existence of the empty set is given as an axiom with the note that said axiom is redundant, and used _for emphasis_.

The next two methods both make use of the axiom of specification. Let us assume for sake of argument that their exists some set $A$. Then by applying specification to $A$ with the formula $x \not = x$, we obtain

$$
\exists B\forall x(x \in B \iff (x \in A \land x \not = x)).
$$

Since $x \not = x$ is clearly false for all $x$, we have that the set $B$ contains no elements. Thus we have that the existence of any set at all implies the existence of the empty set. The only remaining difficulty is proving that some set exists.

The second approach uses the axiom of infinity. Since the axiom of infinity asserts that there does exist a set (which is infinite) we can apply specification to obtain the empty set. This method feels very excessive as a means of postulating that some set exists, as we do so by asserting that their exist infinitely many. Additionally, this poses a problem in presentations like ours which add axioms as they become needed, as we wish to delay the introduction of the axiom of infinity until we examine infinite sets. This leads us to the third approach.

The final way to construct the empty set, and the one taken on this website, is to simply take as a logical axiom that our domain of discourse is not empty, that is $\exists x (x = x)$. Recall the proof given earlier. There are many different formalizations of first order logic, so when working in a logic that allows empty domains of discourse one must necessarily use a different approach. 

We now move on to the proof that the empty set exists, taking the third approach described above. We must first define the empty set.

::: {.callout-note icon="false"}
## Definition

The [empty set]{.definition} is the set containing no elements, and denoted by $\varnothing$. Formally it is the set such that for any $A$,

$$
\varnothing = \{x \in A \mid x \not = x\}.
$$

:::

Now we can show the empty set exists!

::: {.callout-note icon="false"}
## Theorem (Existence of an Empty Set)

The empty set exists.

:::

::: {.callout-tip icon="false" collapse="true"}
## Proof

We will use the technique discussed above. Since we have chosen a logic such that our domain of discourse is not empty, there exists some set $A$. Then by applying the axiom of specification on $A$ with the formula $x \not = x$ we get

$$
B = \{x \in A \mid x \not= x\}.
$$

By our definition, we call notate the set $B$ as $\varnothing$, and thus $\varnothing$ exists. As noted above, if you are uncomfortable with using the non-empty domain of discourse, simply choose $A$ to be the infinite set guaranteed to exist by the axiom of infinity.
:::



## Properties

We must first state a few properties before we can prove the empty set is unique.

::: {.callout-note icon="false"}
## Theorem 

The empty set contains no elements, that is for all $x$

$$
x \not \in \varnothing
$$

:::

::: {.callout-tip icon="false" collapse="true"}
## Proof

Unpacking set builder notation we have that

$$
x \in \varnothing \iff x \in A \land x \not = x.
$$

Since $x \not = x$ is always false and $x$ was arbitrary we have

$$
\forall x(x \not \in \varnothing).
$$

:::

Now we can prove theres only one empty set.

::: {.callout-note icon="false"}
## Theorem (Uniqueness of the Empty Set)

The empty set is unique.

:::

::: {.callout-tip icon="false" collapse="true"}
## Proof

We know now that the empty set exists, specifying it from our given set $A$. However if we substitute $A$ for a different set, will we obtain the same set? Perhaps there are an infinite amount of empty sets $\varnothing_A$, $\varnothing_B$, $\varnothing_C$ and so on depending on which set we specify from? In order to prove that all of these sets are equivalent, we use the axiom of extension.

Suppose that we have two sets $A$ and $B$ and using the axiom of specification constructed two empty sets

$$
\varnothing_A = \{x \in A \mid x \not= x\} \text{ and } \varnothing_B = \{x \in B \mid x \not= x\}.
$$

Both of these sets are empty sets according to our definition. By our previous theorem we have $x \not \in \varnothing_A$ and $x \not \in \varnothing_B$. We can now provide a proof $\varnothing_A$ and $\varnothing_B$ are equivalent using logic.

We have
$$
x \not \in \varnothing_A \land x \not \in \varnothing_B.
$$

Since both formulas are always true[^3], we may write
$$
x \not \in \varnothing_A \iff x \not \in \varnothing_B
$$

and thus by negation

$$
x \in \varnothing_A \iff x \in \varnothing_B.
$$

Since $x$ was arbitrary we have
$$
\forall x (x \in \varnothing_A \iff x \in \varnothing_B).
$$

Finally, applying the axiom of extension we have

$$
\forall x (x \in \varnothing_A \iff x \in \varnothing_B) \implies \varnothing_A = \varnothing_B.
$$

Thus our two empty sets were actually the same set! And therefore the empty set is unique!
:::


[^1]: The following paragraphs follow closely from the answer given by Andrés Caicedo on this [MathExchange](https://math.stackexchange.com/questions/278863/the-existence-of-the-empty-set-is-an-axiom-of-zfc-or-not) form.

[^2]: Enderton, Kunen, Weese & Just

[^3]: Since $x$ is free, we must say it's universal closure $\forall x (x \not\in \varnothing)$ is true.