---
title: "The list"
format:
  html:
    toc: false
    html-math-method: katex
---

The big list

## Explicit

This section takes us through explicit antiderivatives, and the forms we will attempt to convert each integral into.

### Fundamentals

Integrals using only the definition and linearity. Let $F^\prime(x) = f(x)$ and $G^\prime(x) = g(x)$

- $\int f(x) \, dx$
- $\int f(x) + g(x) \, dx$
- $\int k f(x) \, dx$
- $\int -f(x) \, dx$
- $\int af(x) + bg(x) \, dx$

### Inverse power rule

- $\int x \, dx$
- $\int x^2 \, dx$
- $\int 2x^2 - 3x - 1 \, dx$
- $\int 2x(x^2 + 4)^2$

- $\int \frac{1}{x^2} \, dx$
- $\int \frac{3}{x^6} + \frac{7}{x^{10}} - \frac{4}{x^{12}} \, dx$

- $\int \sqrt{x} \, dx$
- $\int \frac{1}{\sqrt{x}} \, dx$
- $\int \sqrt[3]{x} + 2\sqrt[5]{x^2}\, dw$

- $\int x^\pi \, dx$

### Logarithms and Exponents

- $\int e^x \, dx$
- $\int 5e^{5x} \, dx$
- $\int e^{x + a} \, dx$
- $\int \frac{1}{e^x} \, dx$

- $\int a^x \, dx$
- $\int a^{bx} \, dx$

- $\int \frac{1}{x} \, dx$
- $\int \frac{1}{x + a} \, dx$

### Trigonometric Functions

- $\int \sin x \, dx$
- $\int \cos x \, dx$
- $\int \frac{1}{\sin^2 x} \, dx$
- $\int \frac{1}{\cos^2 x} \, dx$
- $\int \frac{\sin x}{\cos^2 x} \, dx$
- $\int \frac{\cos x}{\sin^2 x} \, dx$

- $\int \frac{1}{x^2 + 1} \, dx$
- $\int \frac{1}{\sqrt{1 - x^2}} \, dx$
- $\int \frac{1}{x\sqrt{x^2 - 1}} \, dx$

- $\int \sinh x \, dx$
- $\int \cosh x \, dx$
- $\int \frac{1}{\sinh^2 x} \, dx$
- $\int \frac{1}{\cosh^2 x} \, dx$
- $\int \frac{\sinh x}{\cosh^2 x} \, dx$
- $\int \frac{\cosh x}{\sinh^2 x} \, dx$

- $\int \frac{1}{1 - x^2} \, dx$
- $\int \frac{1}{\sqrt{x^2 + 1}} \, dx$
- $\int \frac{1}{x\sqrt{1 - x^2}} \, dx$

## General Methods

Now we use some methods to expand the number of integrals we can solve.

### Substitution

- $\int 2x(x^2 + 4)^2 \, dx$
- $\int \frac{x}{\sqrt{1-2x^2}} \, dx$

### Integration by parts 

- $\int \ln x \, dx$
- $\int x\ln x \, dx$
- $\int x^2 \ln x \, dx$
- $\int x^n \ln x \, dx$

- $\int \arctan x \, dx$

- $\int e^x \cos x \, dx$
- $\int e^x \sin x \, dx$

### Partial Fraction Decomposition

- $\int \frac{1}{(x-1)(x-2)} \, dx$
- $\int \frac{1}{(x+a)(x+b)} \, dx$
- $\int \frac{x-9}{(x+5)(x-2)} \, dx$
- $\int \frac{x+c}{(x+a)(x+b)} \, dx$

- $\int \frac{x^2}{x^2 - 1} \, dx$
- $\int \frac{x^3 + x^2 + 2x + 1}{(x^2 + 1)(x^2 + 2)} \, dx$ 


## Specialized Methods

### Trigonometric Identities

### Trigonometric Substitution

### Completing the square

### Weirstrass Substitution





https://math.stackexchange.com/questions/967117/integration-of-int-frac1-x1x-frac13